### ISSUE TITLE
applications无法获取k8s集群信息

### ISSUE THREAD

**Issue by zhiqli** [hbstarjason/spinnaker-local#1]
按照readme运行成功以后，localhost:9000/#/applications 只有`No matches found for ''`一行文字显示。
1. 查看front50容器日志
```
ERROR http://spin-clouddriver:7002/applications?restricted=false&expand=true
ERROR http://spin-front50:8080/v2/applications?restricted=false
```
2. 进入容器查看网络情况
![image](https://user-images.githubusercontent.com/3350002/68649260-335c3600-055d-11ea-92ef-bf1b0e1b365a.png)
![image](https://user-images.githubusercontent.com/3350002/68649271-36efbd00-055d-11ea-9d6f-c2cace4010af.png)

**Comment by hbstarjason** [comment]
按照如下步骤检查相关配置：
1、docker-compose.yml文件里，确认本地的kubeconfig文件。
```
volumes:
  - ~/.kube/config:/home/spinnaker/.kube/config
```
确认执行`kubectl --kubeconfig ~/.kube/config get node` 没有问题。
2、检查config/clouddriver.yml文件里的配置。
```
kubernetes:
  enabled: true
  accounts:
  - name: my-k8s-v2-account
    requiredGroupMembership: []
    providerVersion: V2
    permissions: {}
    dockerRegistries: []
    context: XXXXXX
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/spinnaker/.kube/config
    oAuthScopes: []
    onlySpinnakerManaged: false
  primaryAccount: my-k8s-v2-account 
```
执行`kubectl --kubeconfig ~/.kube/config  current-context` 获取到context，替换掉`XXXXXX`
3、执行如下命令：
```
$ docker exec -it spin-clouddriver bash
bash-4.4$ kubectl /home/spinnaker/.kube/config get node 
```
